export const project = [
    {
      id: "1",
      name: "Nutricharge Women World",
      image: "/images/projects/nutricharge.webp",
      des: "Built smooth-animated landing page focused on performance and responsiveness",
      tech_stack: [
        "Bootstrap 5",
        "HTML 5",
        "CSS 3",
        "AOS",
        "GSAP",
        "JavaScript",
      ],
      status: "Live",
      type:"Frontend",
      bgColor: "bg-green-500",
      capBg:"bg-blue-100",
      capText:"text-blue-800",
      capBorder:"border-blue-200",
      link: "https://www.nutricharge.in/nutrichargewomanworld/",
      liveBg:"bg-green-500",
      liveText:"text-white",
    },
    {
      id: "2",
      name: "SIB Infotech",
      image: "/images/projects/sib-infotech.webp",
      des: "A modern website built using Next.js, focusing on speed, SEO, and seamless user experience.",
      tech_stack: [
        "NextJs",
        "Bootstrap 5",
        "Swiper Slider",
        "GSAP",
        "JavaScript",
      ],
      status: "Live",
      type:"Frontend",
      bgColor: "bg-blue-600",
      capBg:"bg-green-100",
      capText:"text-green-800",
      capBorder:"border-green-200",
      link: "https://www.sibinfotech.com/",
      liveBg:"bg-blue-600",
      liveText:"text-white",
    },
    {
      id: "3",
      name: "Manisha Bhandari Mishra",
      image: "/images/projects/manisha.webp",
      des: "A responsive & clean website crafted using Bootstrap 5, HTML, & CSS for modern UI & mobile-first design.",
      tech_stack: [
        "Bootstrap 5",
        "HTML 5",
        "CSS 3",
        "AOS",
        "GSAP",
        "JavaScript",
        "Slick Slider"
      ],
      status: "Completed",
      type:"Frontend",
      bgColor: "bg-purple-600",
      capBg:"bg-orange-100",
      capText:"text-orange-800",
      capBorder:"border-orange-200",
      link: "https://marketingexperts.in/projects/manisha",
      liveBg:"bg-purple-600",
      liveText:"text-white",
    },
     {
      id: "4",
      name: "B.B. Sheep",
      image: "/images/projects/bb-sheep.webp",
      des: "Shopify store with modern design and smart selling features.",
      tech_stack: [
        "Shopify",
        "Payment App",
        "Shipping Carriers",
        "Zapier",
      ],
      status: "Live",
      type:"Customization & edit Liquid File",
      bgColor: "bg-yellow-600",
      capBg:"bg-cyan-100",
      capText:"text-cyan-800",
      capBorder:"border-cyan-200",
      link: "https://www.bbsheep.com/",
      liveBg:"bg-yellow-600",
      liveText:"text-white",
    },
  ];

